name: flutter_tic_tac_toe_sever
description: A dart server for the flutter_tic_tac_toe project
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lints: ^1.0.0
dependencies:
  socket_io: ^1.0.0
  socket_io_client: ^1.0.1
